export const BANNER_AUTOPLAY_ENABLED = true;
export const BANNER_AUTOPLAY_INTERVAL_MS = 5000;
export const BANNER_AUTOPLAY_RESTART_DELAY_MS = 5000;

export const TOAST_DEFAULT_DURATION_MS = 2200;
export const LOADING_MINIMUM_VISIBLE_MS = 300;
